### ISSUE TITLE
Warning: Undefined array key "_mf_captcha_code"

### ISSUE THREAD

**Issue by bomsn** [lichtmetzger/mega-forms-local-captcha#1]
The first load will generate the following warning:

`Warning:  Undefined array key "_mf_captcha_code" in www\wp-content\plugins\mega-forms-local-captcha\src\Views.php on line 24`

Subsequent loads will not trigger the error above. This will probably happen because the session was not stored yet.

This can be solved by replaceing:

`$storedCode = $_SESSION['_mf_captcha_code'];`

With

`$storedCode = $_SESSION['_mf_captcha_code'] ?? '';`

**Comment by lichtmetzger** [comment]
Thank you. This has been fixed in https://github.com/lichtmetzger/mega-forms-local-captcha/commit/c19a975520bc02e44f4b0f11f19dd49bc27311b5
